sudo: false
language: node_js
node_js:
  - '12'
  - '10'
  - '8'

os:
  - linux
  - osx
cache:
  directories:
  - node_modules
after_success:
  - npm run coverage
script:
  - npm test
matrix:
    include:
        - node: '10'
          env: ALPINE=1
          services:
              - docker
          script:
              - docker build . -t pidusage && npm run alpine
